### PR TITLE
feat: Add a custom JSON schema provider for Oxc config files

### LINKED ISSUE #65: Update to associate config files with custom JSON schema
Looks like this is done by implementing JsonSchemaProviderFactory.

### PR DESCRIPTION
**Pull request by nrayburn-tech**
Closes #65.

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
Not related to this pull request.
Can you help to replace all `com.github.iwanabethatguy.oxcintellijplugin` to `com.github.oxc-project.oxcintellijplugin`?

**Comment by nrayburn-tech** [comment]
Sure, I was just waiting to find out what we wanted to use.  I'll put a PR up for that soon.

**Comment by nrayburn-tech** [comment]
Build failure doesn't seem related to my changes.


```
System.IO.IOException: No space left on device : '/home/runner/runners/2.320.0/_diag/Worker_20241013-025200-utc.log'
   at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
   at System.IO.Strategies.BufferedFileStreamStrategy.FlushWrite()
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.Diagnostics.TextWriterTraceListener.Flush()
   at GitHub.Runner.Common.HostTraceListener.WriteHeader(String source, TraceEventType eventType, Int32 id)
   at GitHub.Runner.Common.HostTraceListener.TraceEvent(TraceEventCache eventCache, String source, TraceEventType eventType, Int32 id, String message)
   at System.Diagnostics.TraceSource.TraceEvent(TraceEventType eventType, Int32 id, String message)
   at GitHub.Runner.Worker.Worker.RunAsync(String pipeIn, String pipeOut)
   at GitHub.Runner.Worker.Program.MainAsync(IHostContext context, String[] args)
System.IO.IOException: No space left on device : '/home/runner/runners/2.320.0/_diag/Worker_20241013-025200-utc.log'
   at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
   at System.IO.Strategies.BufferedFileStreamStrategy.FlushWrite()
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.Diagnostics.TextWriterTraceListener.Flush()
   at GitHub.Runner.Common.HostTraceListener.WriteHeader(String source, TraceEventType eventType, Int32 id)
   at GitHub.Runner.Common.HostTraceListener.TraceEvent(TraceEventCache eventCache, String source, TraceEventType eventType, Int32 id, String message)
   at System.Diagnostics.TraceSource.TraceEvent(TraceEventType eventType, Int32 id, String message)
   at GitHub.Runner.Common.Tracing.Error(Exception exception)
   at GitHub.Runner.Worker.Program.MainAsync(IHostContext context, String[] args)
Unhandled exception. System.IO.IOException: No space left on device : '/home/runner/runners/2.320.0/_diag/Worker_20241013-025200-utc.log'
   at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
   at System.IO.Strategies.BufferedFileStreamStrategy.FlushWrite()
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.Diagnostics.TextWriterTraceListener.Flush()
   at System.Diagnostics.TraceSource.Flush()
   at GitHub.Runner.Common.TraceManager.Dispose(Boolean disposing)
   at GitHub.Runner.Common.TraceManager.Dispose()
   at GitHub.Runner.Common.HostContext.Dispose(Boolean disposing)
   at GitHub.Runner.Common.HostContext.Dispose()
   at GitHub.Runner.Worker.Program.Main(String[] args)
```

**Comment by IWANABETHATGUY** [comment]
> Build failure doesn't seem related to my changes.
> 
> ```
> System.IO.IOException: No space left on device : '/home/runner/runners/2.320.0/_diag/Worker_20241013-025200-utc.log'
>    at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
>    at System.IO.Strategies.BufferedFileStreamStrategy.FlushWrite()
>    at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
>    at System.Diagnostics.TextWriterTraceListener.Flush()
>    at GitHub.Runner.Common.HostTraceListener.WriteHeader(String source, TraceEventType eventType, Int32 id)
>    at GitHub.Runner.Common.HostTraceListener.TraceEvent(TraceEventCache eventCache, String source, TraceEventType eventType, Int32 id, String message)
>    at System.Diagnostics.TraceSource.TraceEvent(TraceEventType eventType, Int32 id, String message)
>    at GitHub.Runner.Worker.Worker.RunAsync(String pipeIn, String pipeOut)
>    at GitHub.Runner.Worker.Program.MainAsync(IHostContext context, String[] args)
> System.IO.IOException: No space left on device : '/home/runner/runners/2.320.0/_diag/Worker_20241013-025200-utc.log'
>    at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
>    at System.IO.Strategies.BufferedFileStreamStrategy.FlushWrite()
>    at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
>    at System.Diagnostics.TextWriterTraceListener.Flush()
>    at GitHub.Runner.Common.HostTraceListener.WriteHeader(String source, TraceEventType eventType, Int32 id)
>    at GitHub.Runner.Common.HostTraceListener.TraceEvent(TraceEventCache eventCache, String source, TraceEventType eventType, Int32 id, String message)
>    at System.Diagnostics.TraceSource.TraceEvent(TraceEventType eventType, Int32 id, String message)
>    at GitHub.Runner.Common.Tracing.Error(Exception exception)
>    at GitHub.Runner.Worker.Program.MainAsync(IHostContext context, String[] args)
> Unhandled exception. System.IO.IOException: No space left on device : '/home/runner/runners/2.320.0/_diag/Worker_20241013-025200-utc.log'
>    at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
>    at System.IO.Strategies.BufferedFileStreamStrategy.FlushWrite()
>    at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
>    at System.Diagnostics.TextWriterTraceListener.Flush()
>    at System.Diagnostics.TraceSource.Flush()
>    at GitHub.Runner.Common.TraceManager.Dispose(Boolean disposing)
>    at GitHub.Runner.Common.TraceManager.Dispose()
>    at GitHub.Runner.Common.HostContext.Dispose(Boolean disposing)
>    at GitHub.Runner.Common.HostContext.Dispose()
>    at GitHub.Runner.Worker.Program.Main(String[] args)
> ```

I will revert the renovate bump

**Comment by nrayburn-tech** [comment]
> Not related to this pull request. Can you help to replace all `com.github.iwanabethatguy.oxcintellijplugin` to `com.github.oxc-project.oxcintellijplugin`?

Once all my current PRs get merged in, I'll update this. (It'll be easier without conflicts).

**Pull request merged**
